// Generated by tools/shop-art/render.mjs — don't edit.
// The design's chests: [stage 0 … 4, bursting] per tier, 320×320 (the 240×240 chest
// with 40 px around it), drawn at 2×.
export const CHEST_PAD = 40;
export const CHEST_BOX = 320;
export default {
  basic: [require('../../assets/squad/chests/basic-0.webp'), require('../../assets/squad/chests/basic-1.webp'), require('../../assets/squad/chests/basic-2.webp'), require('../../assets/squad/chests/basic-3.webp'), require('../../assets/squad/chests/basic-4.webp'), require('../../assets/squad/chests/basic-burst.webp')],
  silver: [require('../../assets/squad/chests/silver-0.webp'), require('../../assets/squad/chests/silver-1.webp'), require('../../assets/squad/chests/silver-2.webp'), require('../../assets/squad/chests/silver-3.webp'), require('../../assets/squad/chests/silver-4.webp'), require('../../assets/squad/chests/silver-burst.webp')],
  gold: [require('../../assets/squad/chests/gold-0.webp'), require('../../assets/squad/chests/gold-1.webp'), require('../../assets/squad/chests/gold-2.webp'), require('../../assets/squad/chests/gold-3.webp'), require('../../assets/squad/chests/gold-4.webp'), require('../../assets/squad/chests/gold-burst.webp')],
  crystal: [require('../../assets/squad/chests/crystal-0.webp'), require('../../assets/squad/chests/crystal-1.webp'), require('../../assets/squad/chests/crystal-2.webp'), require('../../assets/squad/chests/crystal-3.webp'), require('../../assets/squad/chests/crystal-4.webp'), require('../../assets/squad/chests/crystal-burst.webp')],
  rainbow: [require('../../assets/squad/chests/rainbow-0.webp'), require('../../assets/squad/chests/rainbow-1.webp'), require('../../assets/squad/chests/rainbow-2.webp'), require('../../assets/squad/chests/rainbow-3.webp'), require('../../assets/squad/chests/rainbow-4.webp'), require('../../assets/squad/chests/rainbow-burst.webp')],
};
