// Decodes the design's screens out of "Squish Squad App.html" (a bundled
// page: every file is a gzip + base64 entry in its __bundler/manifest
// script, named in __bundler/ext_resources) into tools/shop-art/design/,
// under the files' own names ("Loot Chest Art.dc.html", "coin.svg" …),
// plus the app shell ("App Shell.html", from __bundler/template) and the
// .dc.html runtime and data (support.js, squad-store.js,
// creatures-v2.js) from the design zip's handoff/,
// and writes the coin, gem and star icons to src/squad/icons.js.
//
//   node tools/shop-art/extract.mjs
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const OUT = path.join(HERE, 'design');
const html = fs.readFileSync(path.join(ROOT, 'Squish Squad App.html'), 'utf8');
const block = (type) => {
  const i = html.indexOf(`<script type="__bundler/${type}">`);
  const s = html.indexOf('>', i) + 1;
  return JSON.parse(html.slice(s, html.indexOf('</script>', s)).trim());
};
const manifest = block('manifest');
fs.mkdirSync(OUT, { recursive: true });
let n = 0;
for (const { id, uuid } of block('ext_resources')) {
  if (/^https?:/.test(id) || !manifest[uuid]) continue;
  const e = manifest[uuid];
  let buf = Buffer.from(e.data, 'base64');
  if (e.compressed) buf = zlib.gunzipSync(buf);
  const name = decodeURIComponent(id.replace(/^\.\//, '')) + (/\.\w+$/.test(id) ? '' : '.svg');
  fs.writeFileSync(path.join(OUT, name), buf);
  n++;
}
// The app shell (bottom nav, login, daily spin, ad banner) is the bundle's
// __bundler/template: a JSON string of HTML whose resources are referenced
// by uuid.
fs.writeFileSync(path.join(OUT, 'App Shell.html'), block('template'));
n++;
execFileSync('python', ['-c', `import zipfile; z = zipfile.ZipFile(r'${path.join(ROOT, 'ASMR Creature Squash Game.zip')}'); [open(r'${OUT}/' + f, 'wb').write(z.read('handoff/' + f)) for f in ('support.js', 'squad-store.js', 'creatures-v2.js')]`]);
n += 3;
console.log(`${n} files → ${path.relative(ROOT, OUT)}`);

// The currency icons, for <SvgXml>: plain gradients and paths, minus the
// C2PA metadata blob.
let icons = "// Generated by tools/shop-art/extract.mjs from the design's coin.svg, gem.svg and\n// star.svg (metadata stripped) — draw with <SvgXml xml={…} />.\n";
for (const n of ['coin', 'gem', 'star']) {
  const svg = fs
    .readFileSync(path.join(OUT, `${n}.svg`), 'utf8')
    .replace(/<metadata>[\s\S]*?<\/metadata>/g, '')
    .replace(/\s+xmlns:c2pa="[^"]*"/, '')
    .replace(/>\s+</g, '><')
    .trim();
  icons += `export const ${n.toUpperCase()}_SVG = ${JSON.stringify(svg)};\n`;
}
fs.writeFileSync(path.join(ROOT, 'src/squad/icons.js'), icons);
console.log('→ src/squad/icons.js');

// Each squishy's concept, squish sound and signature move (squad-store.js
// roster: [id, name, set, rarity, concept, sound, move, dance]), for the
// Reveal Show and the creature sheet.
const store = fs.readFileSync(path.join(OUT, 'squad-store.js'), 'utf8');
const moves = [...store.matchAll(/\[(\d+), '[^']*', '[a-z]+', \d, '([^']*)', '([^']*)', '([^']*)', '([a-z]+)'/g)].map((m) => [Number(m[1]), m[4], m[5], m[2], m[3]]);
fs.writeFileSync(
  path.join(ROOT, 'src/squad/moves.js'),
  `// Generated by tools/shop-art/extract.mjs from the design's squad-store.js.\n// Each squishy, by roster id: [move name, dance, concept, squish sound].\nexport default ${JSON.stringify(Object.fromEntries(moves.map(([id, ...rest]) => [id, rest])))};\n`,
);
console.log(`→ src/squad/moves.js (${moves.length} moves)`);
