// Generated by tools/audio/encodeCreatureSounds.py — each creature's own
// squish loop (creature id -> file). Don't edit by hand.

export default {
  '0': require('../../assets/audio/creatures/0.ogg'),
  '1': require('../../assets/audio/creatures/1.ogg'),
  '2': require('../../assets/audio/creatures/2.ogg'),
  '3': require('../../assets/audio/creatures/3.ogg'),
  '4': require('../../assets/audio/creatures/4.ogg'),
  '5': require('../../assets/audio/creatures/5.ogg'),
  '6': require('../../assets/audio/creatures/6.ogg'),
  '7': require('../../assets/audio/creatures/7.ogg'),
  '8': require('../../assets/audio/creatures/8.ogg'),
  '9': require('../../assets/audio/creatures/9.ogg'),
  '10': require('../../assets/audio/creatures/10.ogg'),
  '11': require('../../assets/audio/creatures/11.ogg'),
  '12': require('../../assets/audio/creatures/12.ogg'),
  '13': require('../../assets/audio/creatures/13.ogg'),
  '14': require('../../assets/audio/creatures/14.ogg'),
  '15': require('../../assets/audio/creatures/15.ogg'),
  '16': require('../../assets/audio/creatures/16.ogg'),
  '17': require('../../assets/audio/creatures/17.ogg'),
  '18': require('../../assets/audio/creatures/18.ogg'),
  '19': require('../../assets/audio/creatures/19.ogg'),
};
