import { AppState } from 'react-native';
import { Audio } from 'expo-av';
import * as FileSystem from 'expo-file-system';
import EFFECT_FILES from './effectFiles';

// The v3 design's sound: ~40 effects and five music moods, rendered from the
// design's own sfx.js (tools/audio) to files in assets/audio.
//
//   sfx.play('tap')                 one-shot effect
//   const h = sfx.loop('reelLoop')  looping effect → h.setRate(r), h.stop()
//   sfx.music('cozy')               crossfades to that mood (null = silence)
//
// Effects are kept loaded and restarted on each play (a fresh player per
// play is too slow for button taps) — but only a few at a time: every
// expo-av sound is a whole ExoPlayer with its own decoder and threads, and
// keeping all ~30 loaded ran a 2 GB phone out of memory. The least recently
// played effects are released first. Music and effects each have an on/off
// switch (Home → Settings), remembered on the device. The squish screen's
// own squish / coin / release sounds are separate (src/audio/*Sound.js).

// name -> file (generated by tools/audio/encode.py)
const EFFECTS = EFFECT_FILES;

const MUSIC = {
  dream: require('../../assets/audio/music/dream.ogg'),
  party: require('../../assets/audio/music/party.ogg'),
  cozy: require('../../assets/audio/music/cozy.ogg'),
  calm: require('../../assets/audio/music/calm.ogg'),
  mystery: require('../../assets/audio/music/mystery.ogg'),
};

// The files are levelled per group (tools/audio/encode.py); this puts the
// music back under the effects. 0.2 is the design's exact balance — a
// little more, so it's heard on a phone speaker.
const MUSIC_VOLUME = 0.3;
const FADE_IN_MS = 1200;
const FADE_OUT_MS = 900;
// Loaded right away (the rest on first use), so the first tap has a sound.
const WARM = ['tap', 'whoosh'];
// Effects loaded at once, at most (each is one player).
const MAX_LOADED = 8;
// Sounds that repeat faster than they ring out get two players, so a new
// one doesn't cut the last one short.
const VOICES = { boxBell: 2 };

const SETTINGS_PATH = `${FileSystem.documentDirectory}soundSettings.json`;

const state = {
  effectsOn: true,
  musicOn: true,
  players: new Map(), // effect name -> Promise<Sound>
  loops: new Set(),
  track: null, // { name, sound }
  want: null,
  fading: new Map(), // Sound -> interval
  active: AppState.currentState === 'active',
  listeners: new Set(),
};

const quiet = (p) => p && p.catch(() => {});

let modeSet = false;
function setMode() {
  if (modeSet) return;
  modeSet = true;
  // Mix with other audio rather than stopping it, and play in silent mode on
  // iOS like the rest of the app's sounds.
  quiet(Audio.setAudioModeAsync({ playsInSilentModeIOS: true, shouldDuckAndroid: true, staysActiveInBackground: false }));
}

// name -> { voices: Promise<Sound|null>[], next, used }
function entry(name) {
  if (!EFFECTS[name]) return null;
  let e = state.players.get(name);
  if (!e) {
    setMode();
    const load = () =>
      Audio.Sound.createAsync(EFFECTS[name], { shouldPlay: false, volume: 1, progressUpdateIntervalMillis: 60000 })
        .then((r) => r.sound)
        .catch(() => null);
    e = { voices: Array.from({ length: VOICES[name] || 1 }, load), next: 0, used: 0 };
    state.players.set(name, e);
    evict(name);
  }
  e.used = Date.now();
  return e;
}

// Release the least recently played effects beyond MAX_LOADED.
function evict(keep) {
  const loaded = Array.from(state.players.entries()).filter(([n]) => n !== keep && !WARM.includes(n));
  const extra = state.players.size - MAX_LOADED;
  if (extra <= 0) return;
  loaded
    .sort((a, b) => a[1].used - b[1].used)
    .slice(0, extra)
    .forEach(([n, e]) => {
      state.players.delete(n);
      e.voices.forEach((v) => v.then((sound) => sound && quiet(sound.unloadAsync())));
    });
}

// ---- effects ---------------------------------------------------------------

// Load a screen's effects ahead of time: the first play of an effect loads
// its player, which stalls the app for a moment — mid-way through the
// Mystery Box's fast taps that was enough to break the combo.
function preload(names) {
  if (!state.effectsOn) return;
  names.forEach(entry);
}

function play(name, { delay = 0, rate } = {}) {
  if (!state.effectsOn || !state.active) return;
  const go = async () => {
    const e = entry(name);
    if (!e) return;
    const voice = e.voices[e.next];
    e.next = (e.next + 1) % e.voices.length;
    const sound = await voice;
    if (!sound) return;
    // one native call: restart, at this rate if one's given
    quiet(sound.replayAsync(rate ? { rate, shouldCorrectPitch: false } : {}));
  };
  if (delay) setTimeout(go, delay);
  else go();
}

// A looping effect (the reel's ticking, the unlock hold's hum). Each call
// gets its own player so two loops never fight over one.
function loop(name, { volume = 1, rate = 1 } = {}) {
  const handle = { sound: null, stopped: false, volume, rate };
  if (!state.effectsOn || !EFFECTS[name]) return { setRate() {}, setVolume() {}, stop() {} };
  setMode();
  Audio.Sound.createAsync(EFFECTS[name], { shouldPlay: state.active, isLooping: true, volume, rate, shouldCorrectPitch: false, progressUpdateIntervalMillis: 60000 })
    .then(({ sound }) => {
      if (handle.stopped) {
        quiet(sound.unloadAsync());
        return;
      }
      handle.sound = sound;
      state.loops.add(handle);
    })
    .catch(() => {});
  return {
    setRate(r) {
      handle.rate = r;
      if (handle.sound) quiet(handle.sound.setRateAsync(r, false));
    },
    setVolume(v) {
      handle.volume = v;
      if (handle.sound) quiet(handle.sound.setVolumeAsync(v));
    },
    stop() {
      handle.stopped = true;
      state.loops.delete(handle);
      if (handle.sound) quiet(handle.sound.unloadAsync());
    },
  };
}

// ---- music -----------------------------------------------------------------

function fade(sound, from, to, ms, done) {
  const prev = state.fading.get(sound);
  if (prev) clearInterval(prev);
  const steps = Math.max(1, Math.round(ms / 50));
  let i = 0;
  quiet(sound.setVolumeAsync(from));
  const timer = setInterval(() => {
    i++;
    quiet(sound.setVolumeAsync(from + ((to - from) * i) / steps));
    if (i >= steps) {
      clearInterval(timer);
      state.fading.delete(sound);
      done && done();
    }
  }, 50);
  state.fading.set(sound, timer);
}

function stopTrack() {
  const tr = state.track;
  state.track = null;
  if (!tr) return;
  tr.stopped = true;
  if (tr.sound) fade(tr.sound, MUSIC_VOLUME, 0, FADE_OUT_MS, () => quiet(tr.sound.unloadAsync()));
}

function startTrack(name) {
  setMode();
  const tr = { name, sound: null, stopped: false };
  state.track = tr;
  Audio.Sound.createAsync(MUSIC[name], { shouldPlay: state.active, isLooping: true, volume: 0, progressUpdateIntervalMillis: 60000 })
    .then(({ sound }) => {
      if (tr.stopped) {
        quiet(sound.unloadAsync());
        return;
      }
      tr.sound = sound;
      fade(sound, 0, MUSIC_VOLUME, FADE_IN_MS);
    })
    .catch(() => {});
}

function music(name) {
  state.want = name && MUSIC[name] ? name : null;
  if (state.track && state.track.name === state.want && state.musicOn) return;
  stopTrack();
  if (state.want && state.musicOn) startTrack(state.want);
}

// ---- switches ------------------------------------------------------------

function saveSettings() {
  quiet(FileSystem.writeAsStringAsync(SETTINGS_PATH, JSON.stringify({ effects: state.effectsOn, music: state.musicOn })));
}

function notify() {
  state.listeners.forEach((fn) => fn({ effects: state.effectsOn, music: state.musicOn }));
}

function setEffectsOn(on) {
  state.effectsOn = !!on;
  if (!on) Array.from(state.loops).forEach((h) => h.sound && quiet(h.sound.pauseAsync()));
  saveSettings();
  notify();
}

function setMusicOn(on) {
  state.musicOn = !!on;
  if (!on) stopTrack();
  else if (state.want) music(state.want);
  saveSettings();
  notify();
}

// Settings UI subscribes here; returns the unsubscribe.
function subscribe(fn) {
  state.listeners.add(fn);
  fn({ effects: state.effectsOn, music: state.musicOn });
  return () => state.listeners.delete(fn);
}

// Remembered switches, then a few effects warmed up.
async function init() {
  try {
    const info = await FileSystem.getInfoAsync(SETTINGS_PATH);
    if (info.exists) {
      const saved = JSON.parse(await FileSystem.readAsStringAsync(SETTINGS_PATH));
      state.effectsOn = saved.effects !== false;
      state.musicOn = saved.music !== false;
      notify();
      if (!state.musicOn) stopTrack();
    }
  } catch {
    // defaults
  }
  WARM.forEach(entry);
}

// Nothing plays while the app is in the background.
AppState.addEventListener('change', (next) => {
  const active = next === 'active';
  if (active === state.active) return;
  state.active = active;
  const loops = state.effectsOn ? Array.from(state.loops).map((h) => h.sound) : [];
  const sounds = [state.track && state.track.sound, ...loops].filter(Boolean);
  sounds.forEach((s) => quiet(active ? s.playAsync() : s.pauseAsync()));
});

export default { init, preload, play, loop, music, setEffectsOn, setMusicOn, subscribe };
