// Previews the rendered art (render.mjs → out/) in the app before it is
// published: serves out/ over HTTP and writes src/data/devCatalog.js, a
// catalog built from out/manifest.json whose image URLs point at this server.
// With `adb reverse tcp:9500 tcp:9500` the emulator or phone reaches it at
// localhost:9500. To use it, temporarily replace the Firestore catalog in
// App.js with the file's default export (and remove that again after).
//
//   node tools/plush-art/serve.mjs      (Ctrl-C to stop)

import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROSTER } from './roster.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, 'out');
const PORT = Number(process.env.PORT) || 9500;
const DEV_CATALOG = path.resolve(HERE, '../../src/data/devCatalog.js');

const manifest = JSON.parse(fs.readFileSync(path.join(OUT, 'manifest.json'), 'utf8'));
const catalog = ROSTER.filter((c) => manifest[c.id]).map((c) => {
  const e = manifest[c.id];
  const plush = { v: 2 };
  Object.entries(e.art).forEach(([variant, info]) => {
    plush[variant] = { url: `http://localhost:${PORT}/${c.id}/${variant}.webp`, frame: info.frame };
  });
  return { id: String(c.id), name: c.name, description: c.description, order: c.id, plush, rig: e.rig, moves: e.moves };
});
fs.writeFileSync(DEV_CATALOG, `// Generated by tools/plush-art/serve.mjs — a preview catalog served from\n// this PC. Not for the app bundle.\nexport default ${JSON.stringify(catalog)};\n`);
console.log(`wrote ${DEV_CATALOG} (${catalog.length} creatures)`);

http
  .createServer((req, res) => {
    const file = path.join(OUT, decodeURIComponent(req.url.split('?')[0]));
    if (!file.startsWith(OUT) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      res.writeHead(404);
      res.end();
      return;
    }
    res.writeHead(200, { 'Content-Type': file.endsWith('.json') ? 'application/json' : 'image/webp', 'Cache-Control': 'no-cache' });
    fs.createReadStream(file).pipe(res);
  })
  .listen(PORT, () => console.log(`serving ${OUT} on http://localhost:${PORT} — run: adb reverse tcp:${PORT} tcp:${PORT}`));
