"""Turns the design's per-creature squish recordings into the loops the
squish stage plays while a creature is held.

Source: "ASMR Creature Squash Game (1).zip" in the project root, which holds
export/creature-sounds/NN-name.wav — one 8 s stereo recording per creature,
numbered in roster order (01-glorp is creature id 0, 20-cosmo is id 19).
Each has silence at the ends and is not a loop.

For each one:
  · trim the leading/trailing silence,
  · fold the last CROSSFADE_S onto the start (equal-power crossfade) so the
    loop wraps without a click, exactly like the music tracks,
  · mono, and one shared gain for the whole set (loudest peaks at PEAK, in
    the same ballpark as the old slime.wav loop) so every creature sits at
    a consistent level,
  · Ogg Vorbis into assets/audio/creatures/<id>.ogg (about 60 KB each
    instead of 1.4 MB; the loop is started and paused, never replayed, so
    the decoder-restart cost that keeps short effects as WAV doesn't apply).

Then writes src/audio/creatureSquishFiles.js, the id -> require() map the
app bundles.

    python -m pip install --user soundfile numpy   # once
    python tools/audio/encodeCreatureSounds.py
"""
import io
import pathlib
import re
import zipfile

import numpy as np
import soundfile as sf

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent.parent
ZIP = ROOT / 'ASMR Creature Squash Game (1).zip'
OUT = ROOT / 'assets' / 'audio' / 'creatures'
LIST = ROOT / 'src' / 'audio' / 'creatureSquishFiles.js'
PEAK = 0.7
CROSSFADE_S = 0.4
SILENCE = 0.002  # amplitude below which the ends count as silence


def write_ogg(dest, data, sr, level):
    # in blocks: one big write crashes libsndfile's Vorbis encoder
    with sf.SoundFile(dest, 'w', sr, 1, format='OGG', subtype='VORBIS', compression_level=level) as f:
        for i in range(0, len(data), 4096):
            f.write(data[i:i + 4096])


def trim(mono, sr):
    loud = np.abs(mono) > SILENCE
    if not loud.any():
        return mono
    first = int(np.argmax(loud))
    last = len(loud) - int(np.argmax(loud[::-1]))
    # keep a few ms of the natural fade at each end
    pad = int(sr * 0.01)
    return mono[max(0, first - pad):min(len(mono), last + pad)]


def make_loop(mono, sr):
    n = int(sr * CROSSFADE_S)
    if len(mono) < 3 * n:
        return mono
    head = mono[:n]
    tail = mono[-n:]
    t = np.linspace(0, 1, n, dtype=np.float32)
    # equal-power: tail fades out, head fades in
    mixed = tail * np.cos(t * np.pi / 2) + head * np.sin(t * np.pi / 2)
    return np.concatenate([mixed, mono[n:-n]])


zf = zipfile.ZipFile(ZIP)
clips = {}
for name in sorted(zf.namelist()):
    m = re.search(r'creature-sounds/(\d+)-([a-z]+)\.wav$', name)
    if not m:
        continue
    creature_id = int(m.group(1)) - 1
    data, sr = sf.read(io.BytesIO(zf.read(name)), dtype='float32')
    mono = data if data.ndim == 1 else data.mean(axis=1)
    clips[creature_id] = (m.group(2), make_loop(trim(mono, sr), sr), sr)

gain = PEAK / max(np.abs(c[1]).max() for c in clips.values())
OUT.mkdir(parents=True, exist_ok=True)
for old in OUT.glob('*.ogg'):
    old.unlink()
lines = []
total = 0
for creature_id in sorted(clips):
    name, mono, sr = clips[creature_id]
    dest = OUT / f'{creature_id}.ogg'
    write_ogg(dest, mono * gain, sr, 0.5)
    size = dest.stat().st_size
    total += size
    lines.append(f"  '{creature_id}': require('../../assets/audio/creatures/{creature_id}.ogg'),")
    print(f'{creature_id:>2} {name:<11} {len(mono) / sr:5.2f}s  peak {np.abs(mono * gain).max():.2f}  {size / 1024:5.0f} KB')

LIST.write_text(
    '// Generated by tools/audio/encodeCreatureSounds.py — each creature\'s own\n'
    '// squish loop (creature id -> file). Don\'t edit by hand.\n\n'
    'export default {\n' + '\n'.join(lines) + '\n};\n',
    encoding='utf-8',
)
print(f'{len(clips)} loops, {total / 1024:.0f} KB total, gain x{gain:.2f}; wrote {LIST.relative_to(ROOT)}')
