"""Encodes tools/audio/out/*.wav (render.mjs) to the files the app bundles:
  · short effects (up to SHORT_S) as 16-bit WAV: they're replayed often and
    fast (button taps, the Mystery Box's taps), and a WAV restarts without a
    decoder — with Ogg, every replay re-started the Vorbis decoder, which
    was measurably slower on Android;
  · longer effects as Ogg Vorbis (they're played rarely);
  · music as stereo Ogg Vorbis (the reverb gives it width).
Effects are mono (they're short and mostly centred). It also writes
src/audio/effectFiles.js, the list of effect files the app requires.

Levels: the design's mix is quiet (music sits ~16 dB under the effects), so
each group gets one shared gain, keeping the balance inside the group:
  · effects: the loudest (boxOpen) peaks at 0.92 — about the level of the
    app's existing coin/pop sounds;
  · music: the loudest track peaks at 0.92. The app plays music at
    MUSIC_VOLUME (src/audio/sfx.js), which restores the design's
    music-under-effects balance (reported below as "design balance").

    python -m pip install --user soundfile numpy   # once
    python tools/audio/encode.py
"""
import pathlib

import numpy as np
import soundfile as sf

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent.parent
OUT_SFX = ROOT / 'assets' / 'audio' / 'sfx'
OUT_MUSIC = ROOT / 'assets' / 'audio' / 'music'
PEAK = 0.92
SHORT_S = 1.2

def write_ogg(dest, data, sr, level):
    # in blocks: one big write crashes libsndfile's Vorbis encoder
    channels = 1 if data.ndim == 1 else data.shape[1]
    with sf.SoundFile(dest, 'w', sr, channels, format='OGG', subtype='VORBIS', compression_level=level) as f:
        for i in range(0, len(data), 4096):
            f.write(data[i:i + 4096])


wavs = sorted((HERE / 'out').glob('*.wav'))
clips = {w.stem: sf.read(w, dtype='float32') for w in wavs}
is_music = lambda name: name.startswith('music-')
peak = lambda group: max(np.abs(d).max() for n, (d, _) in clips.items() if group(n))
gain_sfx = PEAK / peak(lambda n: not is_music(n))
gain_music = PEAK / peak(is_music)

OUT_SFX.mkdir(parents=True, exist_ok=True)
OUT_MUSIC.mkdir(parents=True, exist_ok=True)
for old in list(OUT_SFX.glob('*.ogg')) + list(OUT_SFX.glob('*.wav')):
    old.unlink()
total = 0
effect_files = {}
for name, (data, sr) in clips.items():
    if is_music(name):
        dest = OUT_MUSIC / f"{name[len('music-'):]}.ogg"
        write_ogg(dest, data * gain_music, sr, 0.55)
    else:
        mono = data.mean(axis=1) * gain_sfx
        if len(mono) / sr <= SHORT_S:
            dest = OUT_SFX / f'{name}.wav'
            sf.write(dest, mono, sr, subtype='PCM_16')
        else:
            dest = OUT_SFX / f'{name}.ogg'
            write_ogg(dest, mono, sr, 0.45)
        effect_files[name] = dest.name
    size = dest.stat().st_size
    total += size
    print(f'{dest.relative_to(ROOT)}  {len(data) / sr:6.2f}s  {size / 1024:7.1f} KB', flush=True)
lines = [f"  {n}: require('../../assets/audio/sfx/{f}')," for n, f in sorted(effect_files.items())]
header = [
    '// Generated by tools/audio/encode.py — the v3 sound effects the app bundles.',
    "// Short ones are WAV (quick to replay), long ones Ogg. Don't edit by hand.",
    '',
    'export default {',
]
(ROOT / 'src' / 'audio' / 'effectFiles.js').write_text('\n'.join(header + lines + ['};', '']), encoding='utf8')
print(f'total {total / 1024 / 1024:.2f} MB · effects gain {gain_sfx:.2f} · music gain {gain_music:.2f}'
      f' · design balance = music volume {gain_sfx / gain_music:.2f}')
